
name: FTP Deploy
on:
  push:
    branches:
      - master # or main, depending on your default branch

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://braderselva.com/git/
          ftp-username: 'braderse'
          ftp-password: '9;dhuQ96SMpF(6' 
